version: '3'
services:
  airflow:
    image: apache/airflow:latest
    ports:
      - 8080:8080
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=${DB_CONNECTION}
      - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
      - AIRFLOW__WEBSERVER__RBAC=True
    command: webserver

  etl:
    build:
      context: .
      dockerfile: Dockerfile.etl
    volumes:
      - ./dags:/opt/airflow/dags
    depends_on:
      - airflow
    environment:
      - AIRFLOW_CONN_REDSHIFT=${REDSHIFT_CONNECTION}